#include "adcMeasurements.h"

Uint16 current_sample_cnt = 0;
MEASUREMENT_TYPE current_offset = MEASUREMENT_CONVERSION(0);

MEASUREMENT_TYPE calculateBatteryVoltage(Uint16 measurement){
	MEASUREMENT_TYPE meas = MEASUREMENT_CONVERSION(measurement);
	return MEASUREMENT_MULTIPLE(MEASUREMENT_MULTIPLE(MAXIMUM_VOLTAGE, MEASUREMENT_DEVIDE(meas, DEVIDER)), BATTERY_VOLTAGE_MULTIPLIER);
}

MEASUREMENT_TYPE calculateInputVoltage(Uint16 measurement){
	MEASUREMENT_TYPE meas = MEASUREMENT_CONVERSION(measurement);
	return MEASUREMENT_MULTIPLE(MEASUREMENT_MULTIPLE(MAXIMUM_VOLTAGE, MEASUREMENT_DEVIDE(meas, DEVIDER)), INPUT_VOLTAGE_MULTIPLIER);
}

MEASUREMENT_TYPE calculateOutputVoltage(Uint16 measurement){
	MEASUREMENT_TYPE meas = MEASUREMENT_CONVERSION(measurement);
	return MEASUREMENT_MULTIPLE(MEASUREMENT_MULTIPLE(MAXIMUM_VOLTAGE, MEASUREMENT_DEVIDE(meas, DEVIDER)), OUTPUT_VOLTAGE_MULTIPLIER);
}

void calculateBatteryCurrentOffset(Uint16 measurement){
	while(current_sample_cnt < CURRENT_SAMPLE){
		current_offset += MEASUREMENT_DEVIDE(MEASUREMENT_CONVERSION(measurement), MEASUREMENT_CONVERSION(100));
		current_sample_cnt++;
		break;
	}
}

MEASUREMENT_TYPE calculateBatteryCurrent(Uint16 measurement){
	MEASUREMENT_TYPE meas = MEASUREMENT_CONVERSION(measurement) - current_offset;
	return MEASUREMENT_MULTIPLE(MEASUREMENT_MULTIPLE(MAXIMUM_CURRENT, MEASUREMENT_DEVIDE(meas, DEVIDER)), BATTERY_CURRENT_MULTIPLIER);
}
